# Generated by Django 4.2 on 2024-04-13 19:09

from django.db import migrations, models
import moodmusic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('mood', models.CharField(choices=[('Angry', 'Angry'), ('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Surprise', 'Surprise')], max_length=50)),
                ('mp3', models.FileField(upload_to=moodmusic.models.get_song_upload_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=moodmusic.models.get_image_upload_path)),
            ],
        ),
    ]
